# You can change this base image to anything else
# But make sure to use the correct version of Java
FROM maven:3.9.6-eclipse-temurin-17

USER root

RUN apt-get update && apt-get install -y docker.io

USER root
